In [3]:
import pandas as pd
import numpy as np
import os 


dataset = pd.read_csv('market_data.csv')
dataset

     youtube  facebook  newspaper  sales
0      84.72     19.20      48.96  12.60
1     351.48     33.96      51.84  25.68
2     135.48     20.88      46.32  14.28
3     116.64      1.80      36.00  11.52
4     318.72     24.00       0.36  20.88
..       ...       ...        ...    ...
166    45.84      4.44      16.56   9.12
167   113.04      5.88       9.72  11.64
168   212.40     11.16       7.68  15.36
169   340.32     50.40      79.44  30.60
170   278.52     10.32      10.44  16.08

[171 rows x 4 columns]

In [4]:

after_drop = dataset.drop('sales', axis =1 )
y = dataset['sales']

dataset.shape


np_array = after_drop.to_numpy()

In [5]:

x1 = dataset['youtube']
x2 = dataset['facebook']
x3 = dataset['newspaper']
#y =  dataset['sales']

n= len(x1)      
x_bais= np.ones((n,1))

x_new = np.append(x_bais ,np_array, axis = 1)   # X

x_new

array([[  1.  ,  84.72,  19.2 ,  48.96],
       [  1.  , 351.48,  33.96,  51.84],
       [  1.  , 135.48,  20.88,  46.32],
       [  1.  , 116.64,   1.8 ,  36.  ],
       [  1.  , 318.72,  24.  ,   0.36],
       [  1.  , 114.84,   1.68,   8.88],
       [  1.  , 348.84,   4.92,  10.2 ],
       [  1.  , 320.28,  52.56,   6.  ],
       [  1.  ,  89.64,  59.28,  54.84],
       [  1.  ,  51.72,  32.04,  42.12],
       [  1.  , 273.6 ,  45.24,  38.4 ],
       [  1.  , 243.  ,  26.76,  37.92],
       [  1.  , 212.4 ,  40.08,  46.44],
       [  1.  , 352.32,  33.24,   2.16],
       [  1.  , 248.28,  10.08,  31.68],
       [  1.  ,  30.12,  30.84,  51.96],
       [  1.  , 210.12,  27.  ,  37.8 ],
       [  1.  , 107.64,  11.88,  42.84],
       [  1.  , 287.88,  49.8 ,  22.2 ],
       [  1.  , 272.64,  18.96,  59.88],
       [  1.  ,  80.28,  14.04,  44.16],
       [  1.  , 239.76,   3.72,  41.52],
       [  1.  , 120.48,  11.52,   4.32],
       [  1.  , 259.68,  50.04,  47.52],
       [  1.  , 219.12,  55.44,  70.44],
       [  1.  , 315.24,  34.56,  19.08],
       [  1.  , 238.68,  59.28,  72.  ],
       [  1.  ,   8.76,  33.72,  49.68],
       [  1.  , 163.44,  23.04,  19.92],
       [  1.  , 252.96,  59.52,  45.24],
       [  1.  , 252.84,  35.4 ,  11.16],
       [  1.  ,  64.2 ,   2.4 ,  25.68],
       [  1.  , 313.56,  51.24,  65.64],
       [  1.  , 287.16,  18.6 ,  32.76],
       [  1.  , 123.24,  35.52,  10.08],
       [  1.  , 157.32,  51.36,  34.68],
       [  1.  ,  82.8 ,  11.16,   1.08],
       [  1.  ,  37.8 ,  29.52,   2.64],
       [  1.  , 167.16,  17.4 ,  12.24],
       [  1.  , 284.88,  33.  ,  13.2 ],
       [  1.  , 260.16,  52.68,  32.64],
       [  1.  , 238.92,  36.72,  46.44],
       [  1.  , 131.76,  17.16,  38.04],
       [  1.  ,  32.16,  39.6 ,  23.16],
       [  1.  , 155.28,   6.84,  37.56],
       [  1.  , 256.08,  29.52,  15.72],
       [  1.  ,  20.28,  52.44, 107.28],
       [  1.  ,  33.  ,   1.92,  24.84],
       [  1.  , 144.6 ,  34.2 ,  17.04],
       [  1.  ,   6.48,  35.88,  11.28],
       [  1.  , 139.2 ,   9.24,  27.72],
       [  1.  ,  91.68,  32.04,  26.76],
       [  1.  , 287.76,   4.92,  44.28],
       [  1.  ,  90.36,  24.36,  39.  ],
       [  1.  ,  82.08,  53.4 ,  42.72],
       [  1.  , 256.2 ,  51.6 ,  40.56],
       [  1.  , 231.84,  22.08,  78.84],
       [  1.  ,  91.56,  33.  ,  19.2 ],
       [  1.  , 132.84,  48.72,  75.84],
       [  1.  , 105.96,  30.6 ,  88.08],
       [  1.  , 131.76,  57.36,  61.68],
       [  1.  , 161.16,   5.88,  11.16],
       [  1.  ,  34.32,   1.8 ,  39.6 ],
       [  1.  , 261.24,  40.2 ,  70.8 ],
       [  1.  , 301.08,  43.8 ,  86.76],
       [  1.  , 128.88,  16.8 ,  13.08],
       [  1.  , 195.96,  37.92,  63.48],
       [  1.  , 237.12,   4.2 ,   7.08],
       [  1.  , 221.88,  25.2 ,  26.4 ],
       [  1.  , 347.64,  50.76,  61.44],
       [  1.  , 162.24,  50.04,  55.08],
       [  1.  , 266.88,   5.16,  59.76],
       [  1.  , 355.68,  43.56, 121.08],
       [  1.  , 336.24,  12.12,  25.68],
       [  1.  , 225.48,  20.64,  21.48],
       [  1.  , 285.84,  41.16,   6.36],
       [  1.  , 165.48,  55.68,  70.8 ],
       [  1.  ,  30.  ,  13.2 ,  35.64],
       [  1.  , 108.48,   0.36,  27.84],
       [  1.  ,  15.72,   0.48,  30.72],
       [  1.  , 306.48,  32.28,   6.6 ],
       [  1.  , 270.96,   9.84,  67.8 ],
       [  1.  , 290.04,  45.6 ,  27.84],
       [  1.  , 210.84,  18.48,   2.88],
       [  1.  , 251.52,  24.72,  12.84],
       [  1.  ,  93.84,  56.16,  41.4 ],
       [  1.  ,  90.12,  42.  ,  63.24],
       [  1.  , 167.04,  17.16,  30.72],
       [  1.  ,  91.68,   0.96,  17.76],
       [  1.  , 150.84,  44.28,  95.04],
       [  1.  ,  23.28,  19.2 ,  26.76],
       [  1.  , 169.56,  32.16,  55.44],
       [  1.  ,  22.56,  26.04,  60.48],
       [  1.  , 268.8 ,   2.88,  18.72],
       [  1.  , 147.72,  41.52,  14.88],
       [  1.  , 275.4 ,  38.76,  89.04],
       [  1.  , 104.64,  14.16,  31.08],
       [  1.  ,   9.36,  46.68,  60.72],
       [  1.  ,  96.24,   0.  ,  11.04],
       [  1.  , 264.36,  58.8 ,   3.84],
       [  1.  ,  71.52,  14.4 ,  51.72],
       [  1.  ,   0.84,  47.52,  10.44],
       [  1.  , 318.24,   3.48,  51.6 ],
       [  1.  ,  10.08,  32.64,   2.52],
       [  1.  , 263.76,  40.2 ,  54.12],
       [  1.  ,  44.28,  46.32,  78.72],
       [  1.  ,  57.96,  56.4 ,  10.2 ],
       [  1.  ,  30.72,  46.8 ,  11.16],
       [  1.  , 328.44,  34.68,  71.64],
       [  1.  ,  51.6 ,  31.08,  24.6 ],
       [  1.  , 221.88,  52.68,   2.04],
       [  1.  ,  88.08,  20.4 ,  15.48],
       [  1.  , 232.44,  42.48,  90.72],
       [  1.  , 264.6 ,  39.84,  45.48],
       [  1.  , 125.52,   6.84,  41.28],
       [  1.  , 115.44,  17.76,  46.68],
       [  1.  , 168.36,   2.28,  10.8 ],
       [  1.  , 288.12,   8.76,  10.44],
       [  1.  , 291.84,  58.8 ,  53.16],
       [  1.  ,  45.6 ,  48.36,  14.28],
       [  1.  ,  53.64,  30.96,  24.72],
       [  1.  , 336.84,  16.68,  44.4 ],
       [  1.  , 145.2 ,  10.08,  58.44],
       [  1.  , 237.12,  27.96,  17.04],
       [  1.  , 205.56,  47.64,  45.24],
       [  1.  , 225.36,  25.32,  11.4 ],
       [  1.  ,   4.92,  13.92,   6.84],
       [  1.  , 112.68,  52.2 ,  60.6 ],
       [  1.  , 179.76,   1.56,  29.16],
       [  1.  ,  14.04,  44.28,  54.24],
       [  1.  , 158.04,  22.08,  41.52],
       [  1.  , 207.  ,  21.72,  36.84],
       [  1.  , 102.84,  42.96,  59.16],
       [  1.  , 226.08,  21.72,  30.72],
       [  1.  , 196.2 ,  44.16,   8.88],
       [  1.  , 140.64,  17.64,   6.48],
       [  1.  , 281.4 ,   4.08, 101.76],
       [  1.  ,  21.48,  45.12,  25.92],
       [  1.  , 248.16,   6.24,  23.28],
       [  1.  , 258.48,  28.32,  69.12],
       [  1.  , 341.16,  12.72,   7.68],
       [  1.  ,  60.  ,  13.92,  22.08],
       [  1.  , 197.4 ,  25.08,  56.88],
       [  1.  ,  23.52,  24.12,  20.4 ],
       [  1.  , 202.08,   8.52,  15.36],
       [  1.  , 266.88,   4.08,  15.72],
       [  1.  , 332.28,  58.68,  50.16],
       [  1.  , 298.08,  36.24,  24.36],
       [  1.  , 204.24,   9.36,  42.24],
       [  1.  , 332.04,   2.76,  28.44],
       [  1.  , 198.72,  12.  ,  21.12],
       [  1.  , 187.92,   3.12,   9.96],
       [  1.  , 262.2 ,   6.48,  32.88],
       [  1.  ,  67.44,   6.84,  35.64],
       [  1.  , 345.12,  51.6 ,  86.16],
       [  1.  , 304.56,  25.56,  36.  ],
       [  1.  , 246.  ,  54.12,  23.52],
       [  1.  , 167.4 ,   2.52,  31.92],
       [  1.  , 229.32,  34.44,  21.84],
       [  1.  , 343.2 ,  16.68,   4.44],
       [  1.  ,  22.44,  14.52,  28.08],
       [  1.  ,  47.4 ,  49.32,   6.96],
       [  1.  ,  90.6 ,  12.96,   7.2 ],
       [  1.  ,  20.64,   4.92,  37.92],
       [  1.  , 200.16,  50.4 ,   4.32],
       [  1.  , 179.64,  42.72,   7.2 ],
       [  1.  ,  45.84,   4.44,  16.56],
       [  1.  , 113.04,   5.88,   9.72],
       [  1.  , 212.4 ,  11.16,   7.68],
       [  1.  , 340.32,  50.4 ,  79.44],
       [  1.  , 278.52,  10.32,  10.44]])

In [6]:

x_new_transpose = np.transpose(x_new)  #X.T

x_new_transpose_dot_x_new = x_new_transpose.dot(x_new)   # (X.T X)

temp_1 = np.linalg.inv(x_new_transpose_dot_x_new) #(X X.T) inverse

temp_2 = x_new_transpose.dot(y)   # X.T * y

theta = temp_1.dot(temp_2)  #(X X.T) inverse * X.T * y



theta_0 = theta[0]
theta_1 = theta[1]
theta_2 = theta[2]
theta_3 = theta[3]
print(theta_0)
print(theta_1)
print(theta_2)
print(theta_3)

3.505870994464999
0.04523544441261529
0.1883978254115084
0.004279491858703244

In [ ]:

def pred_values(theta_0,theta_1,theta_2,theta_3,youtube,facebook,newspaper):
    predicted_value = youtube * theta_1 + facebook * theta_2 + newspaper * theta_3 + theta_0   
    return predicted_value


youtube = 84.72
facebook = 19.20
newspaper = 48.96
print(pred_values(theta_0,theta_1,theta_2,theta_3,youtube,facebook,newspaper))


youtube =351.48
facebook = 33.96
newspaper = 51.84
print(pred_values(theta_0,theta_1,theta_2,theta_3,youtube,facebook,newspaper))


youtube = 29
facebook = 93
newspaper = 96
print(pred_values(theta_0,theta_1,theta_2,theta_3,youtube,facebook,newspaper))